# Generated by Django 4.1 on 2022-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_main', models.CharField(db_index=True, max_length=100)),
                ('cardcode', models.CharField(db_index=True, max_length=100)),
                ('termid', models.CharField(db_index=True, max_length=100)),
                ('token', models.CharField(db_index=True, max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servio',
                'verbose_name_plural': 'Servio',
            },
        ),
    ]
