# Generated by Django 4.1 on 2022-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servio',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
