# Generated by Django 4.1 on 2023-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servio', '0003_servio_token_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servio_pos_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_main', models.CharField(db_index=True, max_length=100)),
                ('cardcode', models.CharField(db_index=True, max_length=100)),
                ('termid', models.CharField(db_index=True, max_length=100)),
                ('token', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token_valid', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Servio POS Server',
                'verbose_name_plural': 'Servio POS Server',
            },
        ),
        migrations.DeleteModel(
            name='Servio',
        ),
    ]
