# Generated by Django 4.1 on 2022-08-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tarif_item_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
