# Generated by Django 4.1 on 2022-08-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_alter_product_tarif_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tarif_item_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
