# Generated by Django 4.1 on 2022-09-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_tarif_item_id_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
