# Generated by Django 4.1 on 2022-09-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_folder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
